const id = "604nomnom.md";
						const collection = "Archive";
						const slug = "604nomnom";
						const body = "# Product Summary\nA YouTube series that I co-founded and produced featuring Vancouver restaurants. At the peak of the channel, it grew from 0 to 15,000 within 3 months. The series was also featured on Vancity Buzz (Daily Hive) with episodes airing on Shaw Multicultural channel.\n\n\n<p><div class=\"video-container\" align=\"center\">\n<iframe style=\"aspect-ratio: 16/9\" width=\"100%\" src=\"https://www.youtube.com/embed/cJZsrQMKuNs?si=lEwH4Vr6TcgMaNDD\" title=\"YouTube video player\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>\n</div></p>\n\n## Product Vision\nThe vision of this YouTube series was to document and highlight local restaurants that produce great food do not have the budget to be advertised by the Marketing arm of a restaurant group or chain. the ecletic and diverse food.\n\n\n\n\n\n## Target Audience\n### The Local Foodie\n\n\n\n### Restaurant Owner\n\n## Episode Format\nIntroduction\n\n\n## Product Marketing\n• We collaborated with the Daily Hive (Formerly Vancity Buzz) as a contributor to help get our which has \n\n## Key learnings & takeaways\n• Restaurants are service-based establishments that require staff to produce and deliver food to their customers. \n\n• Advertising creates an increase demand on the establishment which may disrupt the quality of product being produced by the restaurant. \n\n• Restaurants tend to have low profit-margins due to competitive pricing and high operational costs.\n\n### \n";
						const data = {title:"604NomNom",pubDate:new Date(1330560000000),projectDuration:"3 Months",isDraft:true,description:"A YouTube series featuring Vancouver Restaurants.",role:"Co-Founder, Producer & Video Editor",category:"Video Production",thumbnail:"../../images/portfolio/604nomnom/604nomnom.jpg",alt:"604NomNom",technology:"Adobe Premiere, Adobe After Effcts, Adobe Illustrator, Adobe Photoshop",isLocked:false,cta:"Learn More",deliverables:["Video","YouTube"],carousel:[],hero:"../../images/portfolio/604nomnom/604nomnom.jpg"};
						const _internal = {
							type: 'content',
							filePath: "/Users/jackieho/portfolio2024-final-1/src/content/Archive/604nomnom.md",
							rawData: undefined,
						};

export { _internal, body, collection, data, id, slug };
